### ISSUE TITLE
Sometimes WASM code generates calls to memmove, not runime.memmove

### ISSUE THREAD

**Issue by kyegupov** [tinygo-org/tinygo#124]
E.g. I have a struct "block" with a struct field "header".
An assignment in the form of `header := block.header` sometimes (when LLVM inlining doesn't kick in) generates a code like this:

    i32.const 120
    call $runtime.alloc
    get_local 5
    i32.const 120
    call $memmove

And that causes also `(import "env" "memmove" (func $memmove (type 1)))` to appear, even though we have perfectly good `$runtime.memmove` function.

**Comment by aykevl** [comment]
Interesting. This probably happens in a late stage of the compiler, during WebAssembly codegen. And probably because the value is quite big (120 bytes).
At what optimization level are you running this? The default one, which is `-opt=z`?

I think `runtime.memmove` needs a pragmatic like `//go:export memmove`.

**Comment by deadprogram** [comment]
Is this still an issue with the current `dev` branch?

**Comment by jaddr2line** [comment]
Is this still an issue with the recent addition of a libc for wasm?

**Comment by aykevl** [comment]
No this should be fixed now.
