### ISSUE TITLE
DIfferent behavior in Go 1.19/TinyGo when casting float with negative value to uint

### ISSUE THREAD

**Issue by deadprogram** [tinygo-org/tinygo#3390]
The following program produces different output in Go 1.19 vs. TinyGo:

```go
package main

func main() {
	var vf1 float64 = -5.865784
	var vf2 float64 = 5.865784
	vu1 := uint32(vf1 * 10000)
	vu2 := uint32(vf2 * 10000)
	println(vu1, vu2)
}
```

Running this using Go 1.19 results in:

```
4294908639 58657
```

Running it using TinyGo results in:

```
0 58657
```

**Comment by aykevl** [comment]
Interesting. In this case, I think the behavior is actually correct in both cases. Namely, [the spec says the following](https://go.dev/ref/spec#Conversions):

>  In all non-constant conversions involving floating-point or complex values, if the result type cannot represent the value the conversion succeeds but the result value is implementation-dependent.

As the number -58657.84 cannot be represented as a uint32 (a negative value can never fit in an unsigned integer), the implementation is free to pick a number. Usually this is whatever the underlying architecture uses as a default value for out-of-range values but I believe we have some custom code for this in TinyGo because the native LLVM instruction results in undefined behavior on out-of-range values.
See: https://github.com/tinygo-org/tinygo/issues/276

CC @niaow

**Comment by dgryski** [comment]
So converting to a signed int type first would be "safer" in this case rather than going directly from `float64` to `uint32`?

**Comment by aykevl** [comment]
Depends on what you want. If the value could be negative, converting to a `int32` (or `int64`) first at least gives you a consistent result. But converting a negative float value to an unsigned integer will always be a "weird" value as it's out of range.

Here is a slightly more simplified version of the reproducer:

```go
package main

func main() {
        var vf1 float64 = -5
        var vf2 float64 = 5
        println(uint32(vf1), uint32(vf2))
}
```

**Comment by hollowaykeanho** [comment]
UPDATE:

Sorry all. Please ignore my post here and its associated GitHub sent email.

I shouldn't be seeking 3rd-party validation over this petty matter. I will concentrate more on the standard libraries assimilations development (actual work) rather messing in the forum.

Regards,
Holloway

**Comment by deadprogram** [comment]
Closing since this is undefined behavior. Thanks everyone!
