### ISSUE TITLE
Go linters don't like wasm imports

### ISSUE THREAD

**Issue by mattjohnsonpint** [tinygo-org/tinygo#4372]
When targeting wasi, I may need to import a function from my host.  TinyGo supports either syntax:

```go
//go:wasmimport myHostModule myHostFunction
func myHostFunction(a, b, c uint32)
```

or

```go
//go:wasm-module myHostModule
//export myHostFunction
func myHostFunction(a, b, c uint32)
```

But regardless of which syntax is used, I get linter warnings in VS Code.

With the default `go-staticcheck` linter:

![image](https://github.com/user-attachments/assets/e72a3430-ae45-403e-8c02-3e87006ed014)

Also when switching the linter to `golangci-lint`:

![image](https://github.com/user-attachments/assets/c3cbc5cc-d992-4b18-a580-b10d07bd3984)

This also happens if using `golangci-lint` in a CI job, and they're treated as hard errors.  I can work around it by setting: 

```yaml
issues:
  exclude:
    - "missing function body"
```

in a `.golangci.yml` file, but I think that's probably not the best idea, since I would only want that to apply to wasm imports.  I've tried their `//nolint:all` comment tags, but it doesn't work for this because it's not a specific linting rule but seen as a compile failure - even though TinyGo compiles it properly.

And I can't find any workaround when using the default `go-staticcheck` linter.

Any suggestions?

Thanks.

**Comment by aykevl** [comment]
In this case the linter is wrong, there's no issue with that code (except for the 2nd example, which is somewhat deprecated). That's also why I usually see the advice not to break CI on linter errors: because they are sometimes wrong.

I don't think this is something that's fixable from TinyGo. Ideally, the linters would get an update to recognize `//go:wasmimport` and not report this issue for those functions (you can report an issue there if you like!). `//go:wasmimport` is a standardized pragma by now and not something TinyGo specific.
