### ISSUE TITLE
You cannot yet use the USB port to the Teensy 4.0 as a USB CDC serial port

### ISSUE THREAD

**Issue by boolangery** [tinygo-org/tinygo#4541]
Hey,

I'm a Go developer using this library and this would be very helpful. Can you point me out some resources indicating what's missing so I can maybe draft a Pull request?

Teensy 4.0 board

Thanks!

**Comment by sago35** [comment]
An implementation was created quite some time ago, but due to various circumstances, it hasn't been merged. Additionally, the interface is slightly different from the current USB Device, so it needs to be merged carefully. If you're interested in working on this task, feel free to take it on!

https://github.com/ardnew/tinygo/tree/feature/teensy40-usb

**Comment by boolangery** [comment]
Great thank you I will take a look at it!
